### ISSUE TITLE
Bad parsing: posts without tags get an empty tag

### ISSUE THREAD

**Issue by mlcdf** [imwally/pinboard#4]
Hello Wally,

I found a bug :)

https://github.com/imwally/pinboard/blob/a0e0a7dd936851b660dff37864f1e5e34980aafb/posts.go#L74

If p.tags equals an empty string, then tags equals `[]string{""}` whereas it should be equal to `[]string`. This is due to the way [strings.Split](https://pkg.go.dev/strings#Split) works.

Here is the fix; 

```go
var tags []string
if p.Tags != "" {
    tags = strings.Split(p.Tags, " ")
} else {
    tags = make([]string, 0, 0)
}
```

Thank you for this package,
Have a good day

**Comment by imwally** [comment]
Sorry, I haven't had much time to get around to this but if you're willing to put in a PR I can merge in the changes! 🙂

**Comment by mlcdf** [comment]
Hey! Not worries, I was just cleaning up old issues. :)

I used your lib for a side project, trying to built a CLI for Pinboard but I abandoned the project as I didn't really need one haha.
